"""add report column to analyses

Revision ID: 4ffd9fb83f5f
Revises: 5faf232ff654
Create Date: 2026-08-21 18:17:44.301225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd9fb83f5f'
down_revision: Union[str, Sequence[str], None] = '5faf232ff654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'report')
    # ### end Alembic commands ###
